create table if not exists public.contact_requests (
  id bigint generated by default as identity primary key,
  request_id uuid not null unique default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  email text not null,
  phone_e164 text,
  phone_country text,
  company text not null,
  message text not null,
  source text not null default 'website_contact',
  language text not null default 'pt',
  consent boolean not null,
  consented_at timestamptz not null,
  status text not null default 'new',
  ip_hash text,
  user_agent text,
  constraint contact_requests_name_length check (char_length(name) between 2 and 100),
  constraint contact_requests_email_length check (char_length(email) between 3 and 254),
  constraint contact_requests_email_lowercase check (email = lower(email)),
  constraint contact_requests_phone_pair check (
    (phone_e164 is null and phone_country is null)
    or
    (phone_e164 ~ '^\+[1-9][0-9]{7,14}$' and phone_country ~ '^[A-Z]{2}$')
  ),
  constraint contact_requests_company_length check (char_length(company) between 2 and 120),
  constraint contact_requests_message_length check (char_length(message) between 10 and 5000),
  constraint contact_requests_source check (source = 'website_contact'),
  constraint contact_requests_language check (language in ('pt', 'en')),
  constraint contact_requests_consent check (consent is true),
  constraint contact_requests_status check (status in ('new', 'contacted', 'qualified', 'closed', 'spam')),
  constraint contact_requests_ip_hash check (ip_hash is null or ip_hash ~ '^[a-f0-9]{64}$'),
  constraint contact_requests_user_agent_length check (user_agent is null or char_length(user_agent) <= 500)
);

create index if not exists contact_requests_status_created_at_idx
  on public.contact_requests (status, created_at desc);

create index if not exists contact_requests_email_idx
  on public.contact_requests (email);

create or replace function public.set_contact_requests_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_contact_requests_updated_at on public.contact_requests;
create trigger set_contact_requests_updated_at
before update on public.contact_requests
for each row execute function public.set_contact_requests_updated_at();

alter table public.contact_requests enable row level security;

revoke all on table public.contact_requests from anon, authenticated;
revoke all on sequence public.contact_requests_id_seq from anon, authenticated;
grant select, insert, update on table public.contact_requests to service_role;
grant usage, select on sequence public.contact_requests_id_seq to service_role;

comment on table public.contact_requests is
  'Contact requests submitted through the Vouga website and written only by the server-side Vercel Function.';
